// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Author struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
	Book string `json:"book"`
}

type Book struct {
	ID     int       `json:"id"`
	Title  string    `json:"title"`
	Author []*Author `json:"author"`
}

type ChoiceInput struct {
	QuestionID string `json:"question_id"`
	ChoiceText string `json:"choice_text"`
}

type QuestionInput struct {
	QuestionText string `json:"question_text"`
	PubDate      string `json:"pub_date"`
}
